### ISSUE TITLE
Matching subresources' properties

### ISSUE THREAD

**Issue by Goutte** [remram44/pybabel-godot#11]
Could this also match the subresources of scenes ?

```
[sub_resource type="Resource" id=1]
script = ExtResource( 3 )
title = "level.tutorial.achievement_a.title"
```

Is there any reason for it not to (besides the effort it takes to code it) ?
_Perhaps I'm misusing subresources ?_

**Comment by remram44** [comment]
I think this is supposed to work after #2

**Comment by Goutte** [comment]
Ooops.  I did not see that MR.  I guess I'm using an older version.  Thanks!
