### ISSUE TITLE
Newest version is not uploaded to PyPi

### ISSUE THREAD

**Issue by gilzoide** [remram44/pybabel-godot#12]
I just installed this package using `pip`, following [the documentation on localization using gettext](https://docs.godotengine.org/en/stable/tutorials/i18n/localization_using_gettext.html#creating-the-po-template-pot-using-pybabel), but it did not come with the newest version and I need the support for multiline strings (#10).

I installed from the cloned code and it works great, but nonetheless this newer version should be uploaded to PyPi =]

**Comment by remram44** [comment]
I tagged 1.1 and uploaded it to PyPI!
